name: BSEtest
favicon: null
layout_spectrum: 0.2714137302245945
typography_spectrum: 0.5435807914473116
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8965982424560934
  lightness: 0.5623043642845005
  saturation: 0.18778952350839972
  rhythmicContrast: 0.3631251249462366
purpose: []
